import type { ScheduleGroup, ScheduleRow } from "@/components/scheduling/types";

export const scheduleYears = [2024, 2025, 2026, 2027, 2028, 2029];

export const scheduleGroups: ScheduleGroup[] = [
  { id: "doors", label: "DOORS" },
  { id: "masonry", label: "Masonry" },
  { id: "drywall", label: "Drywall Framing" },
  { id: "mechanical", label: "Mechanical" },
];

export const scheduleRows: ScheduleRow[] = [
  {
    id: "doors-frames",
    label: "Door Frames",
    percentComplete: 85,
    status: "verify",
    groupId: "doors",
    level: 1,
    order: 1,
    bars: [
      { id: "frames-plan", startYear: 2025.35, endYear: 2027.25, color: "brown" },
    ],
  },
  {
    id: "doors-slabs",
    label: "Door Slabs",
    percentComplete: 82,
    status: "on-track",
    groupId: "doors",
    level: 1,
    order: 2,
    bars: [{ id: "slabs-exec", startYear: 2026.2, endYear: 2027.35, color: "blue" }],
  },
  {
    id: "seals-weatherproofing",
    label: "Seals & Weatherproofing",
    percentComplete: 78,
    status: "on-track",
    groupId: "doors",
    level: 1,
    order: 3,
    bars: [{ id: "seals-exec", startYear: 2025.35, endYear: 2026.45, color: "blue" }],
  },
  {
    id: "door-adjustments",
    label: "Door Adjustments",
    percentComplete: 74,
    status: "on-track",
    groupId: "doors",
    level: 1,
    order: 4,
    bars: [{ id: "adjust-exec", startYear: 2025.35, endYear: 2026.65, color: "blue" }],
  },
  {
    id: "block-brick",
    label: "Block/Brick Laid",
    percentComplete: 70,
    status: "on-track",
    groupId: "masonry",
    level: 1,
    order: 5,
    bars: [{ id: "block-exec", startYear: 2025.35, endYear: 2026.45, color: "slate" }],
  },
  {
    id: "reinforcement",
    label: "Reinforcement",
    percentComplete: 69,
    status: "on-track",
    groupId: "masonry",
    level: 1,
    order: 6,
    bars: [{ id: "reinforcement-exec", startYear: 2025.35, endYear: 2026.45, color: "blue" }],
  },
  {
    id: "grouting",
    label: "Grouting",
    percentComplete: 66,
    status: "on-track",
    groupId: "masonry",
    level: 1,
    order: 7,
    bars: [{ id: "grouting-exec", startYear: 2025.35, endYear: 2026.45, color: "blue" }],
  },
  {
    id: "new-activity",
    label: "Framing layout",
    percentComplete: 65,
    status: "on-track",
    groupId: "drywall",
    level: 1,
    order: 8,
    bars: [{ id: "new-activity-exec", startYear: 2024.6, endYear: 2025.55, color: "blue" }],
  },
  {
    id: "stud-framing",
    label: "Stud framing",
    percentComplete: 61,
    status: "on-track",
    groupId: "drywall",
    level: 1,
    order: 9,
    bars: [{ id: "stud-framing-exec", startYear: 2024.9, endYear: 2026.1, color: "blue" }],
  },
  {
    id: "board-installation",
    label: "Board installation",
    percentComplete: 58,
    status: "on-track",
    groupId: "drywall",
    level: 1,
    order: 10,
    bars: [{ id: "board-installation-exec", startYear: 2025.2, endYear: 2026.35, color: "slate" }],
  },
  {
    id: "taping-finishing",
    label: "Taping and finishing",
    percentComplete: 54,
    status: "verify",
    groupId: "drywall",
    level: 1,
    order: 11,
    bars: [{ id: "taping-finishing-exec", startYear: 2025.55, endYear: 2026.7, color: "green" }],
  },
  {
    id: "equipment-set",
    label: "Equipment set",
    percentComplete: 57,
    status: "on-track",
    groupId: "mechanical",
    level: 1,
    order: 12,
    bars: [{ id: "equipment-set-exec", startYear: 2025.15, endYear: 2026.4, color: "blue" }],
  },
  {
    id: "duct-rough-in",
    label: "Duct to rough-in",
    percentComplete: 53,
    status: "on-track",
    groupId: "mechanical",
    level: 1,
    order: 13,
    bars: [{ id: "duct-rough-in-exec", startYear: 2025.35, endYear: 2026.6, color: "slate" }],
  },
  {
    id: "insulation",
    label: "Insulation",
    percentComplete: 49,
    status: "verify",
    groupId: "mechanical",
    level: 1,
    order: 14,
    bars: [{ id: "insulation-exec", startYear: 2025.5, endYear: 2026.8, color: "green" }],
  },
  {
    id: "startup-balancing",
    label: "Start-up and balancing",
    percentComplete: 45,
    status: "on-track",
    groupId: "mechanical",
    level: 1,
    order: 15,
    bars: [{ id: "startup-balancing-exec", startYear: 2025.95, endYear: 2027.1, color: "brown" }],
  },
];
